I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/s2_4.rpy", line 655, in script
    akane_th onegai "อืม…… อันนี้ก็น่ารักดีนะ แต่คงไม่เหมาะกับฉันหรอกมั้ง" with dissolve
OSError: Couldn't find file 'audio/voice/akane/chapter2/chapter2_4/akane_2_4_007.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/s2_4.rpy", line 655, in script
    akane_th onegai "อืม…… อันนี้ก็น่ารักดีนะ แต่คงไม่เหมาะกับฉันหรอกมั้ง" with dissolve
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\exports.py", line 1493, in say
    who(what, *args, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\character.py", line 1394, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\character.py", line 1045, in do_display
    display_say(who,
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\character.py", line 741, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\core.py", line 3022, in interact_core
    renpy.audio.audio.periodic()
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\audio\audio.py", line 1205, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\audio\audio.py", line 1183, in periodic_thread_main
    periodic_pass()
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\audio\audio.py", line 1125, in periodic_pass
    c.periodic()
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\audio\audio.py", line 534, in periodic
    topf = load(filename)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\audio\audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\loader.py", line 672, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'audio/voice/akane/chapter2/chapter2_4/akane_2_4_007.mp3'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
Re:Fragment ~Absolute Ambition~ Demo 0.1.1
Thu Sep 26 23:17:10 2024
