I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/s1_3.rpy", line 3, in script
    show school_classroom_noon with zoom
  File "game/s1_3.rpy", line 3, in <module>
    show school_classroom_noon with zoom
NameError: name 'zoom' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/s1_3.rpy", line 3, in script
    show school_classroom_noon with zoom
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 1359, in execute
    paired = renpy.python.py_eval(self.paired)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/s1_3.rpy", line 3, in <module>
    show school_classroom_noon with zoom
NameError: name 'zoom' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
Re:Fragment ~Absolute Ambition~ Demo 0.1.4
Sat Oct  5 00:02:11 2024
